`00 getting started` Review
colebrookson/eeb-r-manual pull request #9
Opened 2022-08-13 01:13 UTC by colebrookson

2022-08-13 01:24 UTC, cbteaching requested changes
Needs to be fixed here

2022-08-13 01:24 UTC, cbteaching commented on content/markdown/00-getting-started/00-01-downloads.rmd
> +To use the programming language R, you need to have both the R software downloaded, as well as a way to interact with that software. We will use the integrated development environment (IDE) RStudio f
Language is confusing: say "statistical programming language"

2022-08-13 01:24 UTC, cbteaching commented on content/markdown/00-getting-started/00-02-navigating-rstudio.rmd
> +This bottom right corner is where you can see any current plots, and the files on your computer that are in your current working directory #|# LINK TO WORKING DIRECTORIES #|#.
Link is wrong -

2022-08-26 17:18 UTC, shelbyriskin reviewed
Looks good!

2022-08-26 17:18 UTC, shelbyriskin commented on content/markdown/00-getting-started/00-01-downloads.rmd
> +**Author:** Cole Brookson
Did you spell your name right?

2022-08-28 18:41 UTC, merged